---
version: "3.8"

services:
  # my-service-production:
  #   container_name: my-service-production
  #   build:
  #     target: production
  #     context: .
  #     args:
  #       - PORT=${PORT}
  #   ports:
  #     - "${PORT}:${PORT}"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: "512m"
  #       reservations:
  #         cpus: "0.25"
  #         memory: "256m"
  #   depends_on:
  #     - postgres

  # my-service-dev:
  #   container_name: my-service-dev
  #   restart: unless-stopped
  #   env_file: .env
  #   build:
  #     target: dev
  #     context: .
  #     args:
  #       - PORT=${PORT}
  #   ports:
  #     - "${PORT}:${PORT}"
  #     - "9229:9229"
  #   volumes:
  #     - .:/project
  #     - node_modules:/project/node_modules/
  #   depends_on:
  #     - postgres
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: "512m"
  #       reservations:
  #         cpus: "0.25"
  #         memory: "256m"

  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: your_username
      # TODO: Change this to a secure password
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  node_modules:
  postgres_data:
